# Generated by Django 4.2.4 on 2023-09-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('schoolmanagementapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='principal',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='is_principal',
        ),
        migrations.AddField(
            model_name='principal',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='principal_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='principal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='principal',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='principal',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='principal',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='principal',
            name='password',
            field=models.CharField(default=False, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='principal',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='principal_permissions', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='principal',
            name='username',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
